#!/bin/bash
# Proxmox Root Filesystem Safe Cleanup Script
# Generated by Proxmox Agent

echo "🧹 Starting Proxmox Root Filesystem Cleanup..."
echo "================================================"

# Function to show disk space before/after
show_space() {
    echo "📊 Current disk space:"
    df -h / | grep -v Filesystem
    echo ""
}

echo "📊 BEFORE CLEANUP:"
show_space

# 1. Clean system logs (SAFE)
echo "🗑️  Cleaning system logs..."
journalctl --vacuum-time=7d
find /var/log -type f -name '*.log.*' -mtime +7 -delete 2>/dev/null
find /var/log -type f -name '*.gz' -mtime +14 -delete 2>/dev/null
echo "✅ System logs cleaned"

echo ""
show_space

# 2. Clean package cache (SAFE)
echo "🗑️  Cleaning package cache..."
apt clean
apt autoclean
apt autoremove -y
echo "✅ Package cache cleaned"

echo ""
show_space

# 3. Clean temporary files (SAFE)
echo "🗑️  Cleaning temporary files..."
find /tmp -type f -mtime +7 -delete 2>/dev/null
find /var/tmp -type f -mtime +7 -delete 2>/dev/null
echo "✅ Temporary files cleaned"

echo ""
show_space

# 4. Clean core dumps (SAFE)
echo "🗑️  Cleaning core dumps..."
find / -name 'core.*' -delete 2>/dev/null
find / -name '*.core' -delete 2>/dev/null
echo "✅ Core dumps cleaned"

echo ""
show_space

# 5. Proxmox log cleanup (MEDIUM RISK - review first)
echo "⚠️  Proxmox log cleanup (review recommended)..."
echo "   To clean Proxmox logs manually, run:"
echo "   find /var/log/pve* -type f -mtime +30 -delete"
echo "   logrotate -f /etc/logrotate.conf"

# 6. Old kernel cleanup (MEDIUM RISK - review first)
echo "⚠️  Old kernel cleanup (review recommended)..."
echo "   Current kernels installed:"
dpkg --list | grep linux-image | grep -v meta
echo ""
echo "   To remove old kernels, run: apt autoremove --purge"

echo ""
echo "📊 FINAL DISK SPACE:"
show_space

echo ""
echo "🎉 Safe cleanup completed!"
echo "⚠️  For additional space recovery, review the medium-risk items above"
