# Serena project configuration for proxmox-agent
project_root: /mnt/c/GIT/proxmox-agent

# language of the project
language: python

# whether to use the project's gitignore file to ignore files
ignore_all_files_in_gitignore: true

# list of additional paths to ignore
ignored_paths: []

# whether the project is in read-only mode
read_only: false

# list of tool names to exclude
excluded_tools: []